version: '3.4'

services:
  ioka.services.identityserver:
    image: ${DOCKER_REGISTRY-}iokaservicesidentityserver
    build:
      context: .
      dockerfile: Ioka.Services.IdentityServer/Dockerfile
  ioka.services.demo:
    image: ${DOCKER_REGISTRY-}iokaservicesdemo
    build:
      context: .
      dockerfile: Ioka.Services.Demo/Dockerfile
  elk:
    image: sebp/elk
    volumes:
      - elk-data:/var/lib/elasticsearch
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"

volumes:
  elk-data: